{% set name = "wcosmo" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wcosmo-{{ version }}.tar.gz
  sha256: 9efaf2e6b2cf5aa3a9f3cb9631f04d32f59e242805ed36c76237f4f4fc916d94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - numpy
    - scipy
    - astropy-base

test:
  imports:
    - wcosmo
    - wcosmo.utils
  commands:
    - pip check
    - python -m pytest --pyargs wcosmo.test
  requires:
    - pip
    - pytest
    - gwpopulation >=1

about:
  home: https://github.com/ColmTalbot/wcosmo
  summary: A package for cosmology calculations with arbitrary numpy-like APIs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
